spring:
  profiles:
    active: dev

  mvc:
    hiddenmethod:
      filter:
        enabled: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"