spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    #    baseline-on-migrate: true # 기존 DB가 있을 때 필수
    locations: classpath:db/migration
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  messages:
    basename: messages/messages-ko
    encoding: UTF-8

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
    - classpath*:store/csolved/csolved/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: INFO