spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/csolved
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  messages:
    basename: messages/messages-ko
    encoding: UTF-8

mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml
    - classpath*:store/csolved/csolved/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${BUCKET_NAME}
    region: ${AWS_REGION}

logging:
  level:
    #    web: DEBUG
    root: INFO
    store.csolved.csolved.domain.user.mapper: TRACE

